// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/guildenstern70/smartgorest/ent/phone"
	"github.com/guildenstern70/smartgorest/ent/predicate"
)

// PhoneUpdate is the builder for updating Phone entities.
type PhoneUpdate struct {
	config
	hooks    []Hook
	mutation *PhoneMutation
}

// Where appends a list predicates to the PhoneUpdate builder.
func (_u *PhoneUpdate) Where(ps ...predicate.Phone) *PhoneUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPrefix sets the "prefix" field.
func (_u *PhoneUpdate) SetPrefix(v string) *PhoneUpdate {
	_u.mutation.SetPrefix(v)
	return _u
}

// SetNillablePrefix sets the "prefix" field if the given value is not nil.
func (_u *PhoneUpdate) SetNillablePrefix(v *string) *PhoneUpdate {
	if v != nil {
		_u.SetPrefix(*v)
	}
	return _u
}

// SetNumber sets the "number" field.
func (_u *PhoneUpdate) SetNumber(v string) *PhoneUpdate {
	_u.mutation.SetNumber(v)
	return _u
}

// SetNillableNumber sets the "number" field if the given value is not nil.
func (_u *PhoneUpdate) SetNillableNumber(v *string) *PhoneUpdate {
	if v != nil {
		_u.SetNumber(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *PhoneUpdate) SetKind(v phone.Kind) *PhoneUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *PhoneUpdate) SetNillableKind(v *phone.Kind) *PhoneUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// Mutation returns the PhoneMutation object of the builder.
func (_u *PhoneUpdate) Mutation() *PhoneMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PhoneUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PhoneUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PhoneUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PhoneUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PhoneUpdate) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := phone.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Phone.kind": %w`, err)}
		}
	}
	return nil
}

func (_u *PhoneUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(phone.Table, phone.Columns, sqlgraph.NewFieldSpec(phone.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Prefix(); ok {
		_spec.SetField(phone.FieldPrefix, field.TypeString, value)
	}
	if value, ok := _u.mutation.Number(); ok {
		_spec.SetField(phone.FieldNumber, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(phone.FieldKind, field.TypeEnum, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{phone.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PhoneUpdateOne is the builder for updating a single Phone entity.
type PhoneUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PhoneMutation
}

// SetPrefix sets the "prefix" field.
func (_u *PhoneUpdateOne) SetPrefix(v string) *PhoneUpdateOne {
	_u.mutation.SetPrefix(v)
	return _u
}

// SetNillablePrefix sets the "prefix" field if the given value is not nil.
func (_u *PhoneUpdateOne) SetNillablePrefix(v *string) *PhoneUpdateOne {
	if v != nil {
		_u.SetPrefix(*v)
	}
	return _u
}

// SetNumber sets the "number" field.
func (_u *PhoneUpdateOne) SetNumber(v string) *PhoneUpdateOne {
	_u.mutation.SetNumber(v)
	return _u
}

// SetNillableNumber sets the "number" field if the given value is not nil.
func (_u *PhoneUpdateOne) SetNillableNumber(v *string) *PhoneUpdateOne {
	if v != nil {
		_u.SetNumber(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *PhoneUpdateOne) SetKind(v phone.Kind) *PhoneUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *PhoneUpdateOne) SetNillableKind(v *phone.Kind) *PhoneUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// Mutation returns the PhoneMutation object of the builder.
func (_u *PhoneUpdateOne) Mutation() *PhoneMutation {
	return _u.mutation
}

// Where appends a list predicates to the PhoneUpdate builder.
func (_u *PhoneUpdateOne) Where(ps ...predicate.Phone) *PhoneUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PhoneUpdateOne) Select(field string, fields ...string) *PhoneUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Phone entity.
func (_u *PhoneUpdateOne) Save(ctx context.Context) (*Phone, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PhoneUpdateOne) SaveX(ctx context.Context) *Phone {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PhoneUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PhoneUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PhoneUpdateOne) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := phone.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Phone.kind": %w`, err)}
		}
	}
	return nil
}

func (_u *PhoneUpdateOne) sqlSave(ctx context.Context) (_node *Phone, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(phone.Table, phone.Columns, sqlgraph.NewFieldSpec(phone.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Phone.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, phone.FieldID)
		for _, f := range fields {
			if !phone.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != phone.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Prefix(); ok {
		_spec.SetField(phone.FieldPrefix, field.TypeString, value)
	}
	if value, ok := _u.mutation.Number(); ok {
		_spec.SetField(phone.FieldNumber, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(phone.FieldKind, field.TypeEnum, value)
	}
	_node = &Phone{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{phone.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
