// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/guildenstern70/smartgorest/ent/phone"
)

// PhoneCreate is the builder for creating a Phone entity.
type PhoneCreate struct {
	config
	mutation *PhoneMutation
	hooks    []Hook
}

// SetPrefix sets the "prefix" field.
func (_c *PhoneCreate) SetPrefix(v string) *PhoneCreate {
	_c.mutation.SetPrefix(v)
	return _c
}

// SetNillablePrefix sets the "prefix" field if the given value is not nil.
func (_c *PhoneCreate) SetNillablePrefix(v *string) *PhoneCreate {
	if v != nil {
		_c.SetPrefix(*v)
	}
	return _c
}

// SetNumber sets the "number" field.
func (_c *PhoneCreate) SetNumber(v string) *PhoneCreate {
	_c.mutation.SetNumber(v)
	return _c
}

// SetNillableNumber sets the "number" field if the given value is not nil.
func (_c *PhoneCreate) SetNillableNumber(v *string) *PhoneCreate {
	if v != nil {
		_c.SetNumber(*v)
	}
	return _c
}

// SetKind sets the "kind" field.
func (_c *PhoneCreate) SetKind(v phone.Kind) *PhoneCreate {
	_c.mutation.SetKind(v)
	return _c
}

// Mutation returns the PhoneMutation object of the builder.
func (_c *PhoneCreate) Mutation() *PhoneMutation {
	return _c.mutation
}

// Save creates the Phone in the database.
func (_c *PhoneCreate) Save(ctx context.Context) (*Phone, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PhoneCreate) SaveX(ctx context.Context) *Phone {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PhoneCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PhoneCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PhoneCreate) defaults() {
	if _, ok := _c.mutation.Prefix(); !ok {
		v := phone.DefaultPrefix
		_c.mutation.SetPrefix(v)
	}
	if _, ok := _c.mutation.Number(); !ok {
		v := phone.DefaultNumber
		_c.mutation.SetNumber(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PhoneCreate) check() error {
	if _, ok := _c.mutation.Prefix(); !ok {
		return &ValidationError{Name: "prefix", err: errors.New(`ent: missing required field "Phone.prefix"`)}
	}
	if _, ok := _c.mutation.Number(); !ok {
		return &ValidationError{Name: "number", err: errors.New(`ent: missing required field "Phone.number"`)}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "Phone.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := phone.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Phone.kind": %w`, err)}
		}
	}
	return nil
}

func (_c *PhoneCreate) sqlSave(ctx context.Context) (*Phone, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PhoneCreate) createSpec() (*Phone, *sqlgraph.CreateSpec) {
	var (
		_node = &Phone{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(phone.Table, sqlgraph.NewFieldSpec(phone.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Prefix(); ok {
		_spec.SetField(phone.FieldPrefix, field.TypeString, value)
		_node.Prefix = value
	}
	if value, ok := _c.mutation.Number(); ok {
		_spec.SetField(phone.FieldNumber, field.TypeString, value)
		_node.Number = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(phone.FieldKind, field.TypeEnum, value)
		_node.Kind = value
	}
	return _node, _spec
}

// PhoneCreateBulk is the builder for creating many Phone entities in bulk.
type PhoneCreateBulk struct {
	config
	err      error
	builders []*PhoneCreate
}

// Save creates the Phone entities in the database.
func (_c *PhoneCreateBulk) Save(ctx context.Context) ([]*Phone, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Phone, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PhoneMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PhoneCreateBulk) SaveX(ctx context.Context) []*Phone {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PhoneCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PhoneCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
