// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/guildenstern70/smartgorest/ent/person"
	"github.com/guildenstern70/smartgorest/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	personFields := schema.Person{}.Fields()
	_ = personFields
	// personDescFirstName is the schema descriptor for first_name field.
	personDescFirstName := personFields[0].Descriptor()
	// person.DefaultFirstName holds the default value on creation for the first_name field.
	person.DefaultFirstName = personDescFirstName.Default.(string)
	// personDescLastName is the schema descriptor for last_name field.
	personDescLastName := personFields[1].Descriptor()
	// person.DefaultLastName holds the default value on creation for the last_name field.
	person.DefaultLastName = personDescLastName.Default.(string)
	// personDescAge is the schema descriptor for age field.
	personDescAge := personFields[2].Descriptor()
	// person.DefaultAge holds the default value on creation for the age field.
	person.DefaultAge = personDescAge.Default.(int)
}
