// Code generated by ent, DO NOT EDIT.

package phone

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the phone type in the database.
	Label = "phone"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPrefix holds the string denoting the prefix field in the database.
	FieldPrefix = "prefix"
	// FieldNumber holds the string denoting the number field in the database.
	FieldNumber = "number"
	// FieldKind holds the string denoting the kind field in the database.
	FieldKind = "kind"
	// Table holds the table name of the phone in the database.
	Table = "phones"
)

// Columns holds all SQL columns for phone fields.
var Columns = []string{
	FieldID,
	FieldPrefix,
	FieldNumber,
	FieldKind,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "phones"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"person_phones",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultPrefix holds the default value on creation for the "prefix" field.
	DefaultPrefix string
	// DefaultNumber holds the default value on creation for the "number" field.
	DefaultNumber string
)

// Kind defines the type for the "kind" enum field.
type Kind string

// Kind values.
const (
	KindCellular Kind = "cellular"
	KindHome     Kind = "home"
	KindWork     Kind = "work"
)

func (k Kind) String() string {
	return string(k)
}

// KindValidator is a validator for the "kind" field enum values. It is called by the builders before save.
func KindValidator(k Kind) error {
	switch k {
	case KindCellular, KindHome, KindWork:
		return nil
	default:
		return fmt.Errorf("phone: invalid enum value for kind field: %q", k)
	}
}

// OrderOption defines the ordering options for the Phone queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPrefix orders the results by the prefix field.
func ByPrefix(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrefix, opts...).ToFunc()
}

// ByNumber orders the results by the number field.
func ByNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNumber, opts...).ToFunc()
}

// ByKind orders the results by the kind field.
func ByKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKind, opts...).ToFunc()
}
