// Code generated by ent, DO NOT EDIT.

package phone

import (
	"entgo.io/ent/dialect/sql"
	"github.com/guildenstern70/smartgorest/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Phone {
	return predicate.Phone(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Phone {
	return predicate.Phone(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Phone {
	return predicate.Phone(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Phone {
	return predicate.Phone(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Phone {
	return predicate.Phone(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Phone {
	return predicate.Phone(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Phone {
	return predicate.Phone(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Phone {
	return predicate.Phone(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Phone {
	return predicate.Phone(sql.FieldLTE(FieldID, id))
}

// Prefix applies equality check predicate on the "prefix" field. It's identical to PrefixEQ.
func Prefix(v string) predicate.Phone {
	return predicate.Phone(sql.FieldEQ(FieldPrefix, v))
}

// Number applies equality check predicate on the "number" field. It's identical to NumberEQ.
func Number(v string) predicate.Phone {
	return predicate.Phone(sql.FieldEQ(FieldNumber, v))
}

// PrefixEQ applies the EQ predicate on the "prefix" field.
func PrefixEQ(v string) predicate.Phone {
	return predicate.Phone(sql.FieldEQ(FieldPrefix, v))
}

// PrefixNEQ applies the NEQ predicate on the "prefix" field.
func PrefixNEQ(v string) predicate.Phone {
	return predicate.Phone(sql.FieldNEQ(FieldPrefix, v))
}

// PrefixIn applies the In predicate on the "prefix" field.
func PrefixIn(vs ...string) predicate.Phone {
	return predicate.Phone(sql.FieldIn(FieldPrefix, vs...))
}

// PrefixNotIn applies the NotIn predicate on the "prefix" field.
func PrefixNotIn(vs ...string) predicate.Phone {
	return predicate.Phone(sql.FieldNotIn(FieldPrefix, vs...))
}

// PrefixGT applies the GT predicate on the "prefix" field.
func PrefixGT(v string) predicate.Phone {
	return predicate.Phone(sql.FieldGT(FieldPrefix, v))
}

// PrefixGTE applies the GTE predicate on the "prefix" field.
func PrefixGTE(v string) predicate.Phone {
	return predicate.Phone(sql.FieldGTE(FieldPrefix, v))
}

// PrefixLT applies the LT predicate on the "prefix" field.
func PrefixLT(v string) predicate.Phone {
	return predicate.Phone(sql.FieldLT(FieldPrefix, v))
}

// PrefixLTE applies the LTE predicate on the "prefix" field.
func PrefixLTE(v string) predicate.Phone {
	return predicate.Phone(sql.FieldLTE(FieldPrefix, v))
}

// PrefixContains applies the Contains predicate on the "prefix" field.
func PrefixContains(v string) predicate.Phone {
	return predicate.Phone(sql.FieldContains(FieldPrefix, v))
}

// PrefixHasPrefix applies the HasPrefix predicate on the "prefix" field.
func PrefixHasPrefix(v string) predicate.Phone {
	return predicate.Phone(sql.FieldHasPrefix(FieldPrefix, v))
}

// PrefixHasSuffix applies the HasSuffix predicate on the "prefix" field.
func PrefixHasSuffix(v string) predicate.Phone {
	return predicate.Phone(sql.FieldHasSuffix(FieldPrefix, v))
}

// PrefixEqualFold applies the EqualFold predicate on the "prefix" field.
func PrefixEqualFold(v string) predicate.Phone {
	return predicate.Phone(sql.FieldEqualFold(FieldPrefix, v))
}

// PrefixContainsFold applies the ContainsFold predicate on the "prefix" field.
func PrefixContainsFold(v string) predicate.Phone {
	return predicate.Phone(sql.FieldContainsFold(FieldPrefix, v))
}

// NumberEQ applies the EQ predicate on the "number" field.
func NumberEQ(v string) predicate.Phone {
	return predicate.Phone(sql.FieldEQ(FieldNumber, v))
}

// NumberNEQ applies the NEQ predicate on the "number" field.
func NumberNEQ(v string) predicate.Phone {
	return predicate.Phone(sql.FieldNEQ(FieldNumber, v))
}

// NumberIn applies the In predicate on the "number" field.
func NumberIn(vs ...string) predicate.Phone {
	return predicate.Phone(sql.FieldIn(FieldNumber, vs...))
}

// NumberNotIn applies the NotIn predicate on the "number" field.
func NumberNotIn(vs ...string) predicate.Phone {
	return predicate.Phone(sql.FieldNotIn(FieldNumber, vs...))
}

// NumberGT applies the GT predicate on the "number" field.
func NumberGT(v string) predicate.Phone {
	return predicate.Phone(sql.FieldGT(FieldNumber, v))
}

// NumberGTE applies the GTE predicate on the "number" field.
func NumberGTE(v string) predicate.Phone {
	return predicate.Phone(sql.FieldGTE(FieldNumber, v))
}

// NumberLT applies the LT predicate on the "number" field.
func NumberLT(v string) predicate.Phone {
	return predicate.Phone(sql.FieldLT(FieldNumber, v))
}

// NumberLTE applies the LTE predicate on the "number" field.
func NumberLTE(v string) predicate.Phone {
	return predicate.Phone(sql.FieldLTE(FieldNumber, v))
}

// NumberContains applies the Contains predicate on the "number" field.
func NumberContains(v string) predicate.Phone {
	return predicate.Phone(sql.FieldContains(FieldNumber, v))
}

// NumberHasPrefix applies the HasPrefix predicate on the "number" field.
func NumberHasPrefix(v string) predicate.Phone {
	return predicate.Phone(sql.FieldHasPrefix(FieldNumber, v))
}

// NumberHasSuffix applies the HasSuffix predicate on the "number" field.
func NumberHasSuffix(v string) predicate.Phone {
	return predicate.Phone(sql.FieldHasSuffix(FieldNumber, v))
}

// NumberEqualFold applies the EqualFold predicate on the "number" field.
func NumberEqualFold(v string) predicate.Phone {
	return predicate.Phone(sql.FieldEqualFold(FieldNumber, v))
}

// NumberContainsFold applies the ContainsFold predicate on the "number" field.
func NumberContainsFold(v string) predicate.Phone {
	return predicate.Phone(sql.FieldContainsFold(FieldNumber, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v Kind) predicate.Phone {
	return predicate.Phone(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v Kind) predicate.Phone {
	return predicate.Phone(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...Kind) predicate.Phone {
	return predicate.Phone(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...Kind) predicate.Phone {
	return predicate.Phone(sql.FieldNotIn(FieldKind, vs...))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Phone) predicate.Phone {
	return predicate.Phone(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Phone) predicate.Phone {
	return predicate.Phone(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Phone) predicate.Phone {
	return predicate.Phone(sql.NotPredicates(p))
}
