// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Person is the predicate function for person builders.
type Person func(*sql.Selector)

// Phone is the predicate function for phone builders.
type Phone func(*sql.Selector)
